### ISSUE TITLE
TODO: Update `Entrypoint` in denops-core

### ISSUE THREAD

**Issue by Milly** [vim-denops/denops.vim#349]
After <del>#335</del> #385 is merged.

- [x] Update `Entrypoint` in [denops-core](https://github.com/vim-denops/deno-denops-core).
- [x] Remove *denops\@denops-private\plugin.ts* module from `$.test.exclude` in *deno.jsonc*.
- [x] Remove *denops\@denops-private\plugin.ts* module.
- [x] Change all imports that reference `Entrypoint`.

**Comment by lambdalisue** [comment]
Please starts from https://github.com/vim-denops/deno-denops-core/pull/8
